[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts =
    -ra
    --strict-markers
    --reuse-db
    --cov=accounts
    --cov=projects
    --cov=tasks
    --cov=ai_assistant
    --cov-report=term-missing
testpaths =
    accounts
    projects
    tasks
    ai_assistant
filterwarnings =
    ignore::DeprecationWarning
