# Generated by Django 6.0.5 on 2026-05-23 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('description', 'Опис задачі'), ('categorization', 'Категоризація'), ('chat', 'Чат-помічник'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Тип')),
                ('prompt', models.TextField(verbose_name='Запит')),
                ('response', models.TextField(blank=True, verbose_name='Відповідь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'AI-підказка',
                'verbose_name_plural': 'AI-підказки',
                'ordering': ['-created_at'],
            },
        ),
    ]
